"""Streaming LangGraph agent service for real-time chat responses.

This module provides streaming capabilities for the chatbot, sending tokens
as they are generated by the LLM via Server-Sent Events (SSE).
"""

import json
import logging
from typing import AsyncGenerator

from langchain_core.messages import AIMessage, HumanMessage
from langchain_openai import ChatOpenAI

from app.config import get_settings

settings = get_settings()
logger = logging.getLogger(__name__)


async def stream_chat_response(
    user_message: str,
    session_id: str,
    conversation_history: list[dict] | None = None,
) -> AsyncGenerator[str, None]:
    """Stream chat response tokens in real-time.

    Yields Server-Sent Events formatted strings for each token or event.

    Args:
        user_message: The user's input message
        session_id: Unique identifier for the conversation session
        conversation_history: Optional previous messages for context
    """
    # Build message history
    messages = []
    if conversation_history:
        for msg in conversation_history:
            if msg["role"] == "user":
                messages.append(HumanMessage(content=msg["content"]))
            elif msg["role"] == "assistant":
                messages.append(AIMessage(content=msg["content"]))

    messages.append(HumanMessage(content=user_message))

    # Initialize LLM with streaming enabled
    llm = ChatOpenAI(
        model=settings.LLM_MODEL,
        temperature=settings.LLM_TEMPERATURE,
        max_tokens=settings.LLM_MAX_TOKENS,
        api_key=settings.LLM_API_KEY,
        base_url=settings.LLM_BASE_URL,
        streaming=True,
    )

    # Track if tools are being used
    tools = []
    try:
        # Check if the model decides to call tools by first doing a non-streaming check
        llm_check = ChatOpenAI(
            model=settings.LLM_MODEL,
            temperature=settings.LLM_TEMPERATURE,
            max_tokens=settings.LLM_MAX_TOKENS,
            api_key=settings.LLM_API_KEY,
            base_url=settings.LLM_BASE_URL,
            streaming=False,
        )

        # Check response for tool calls
        check_response = await llm_check.ainvoke(messages)

        if hasattr(check_response, "tool_calls") and check_response.tool_calls:
            # Tool calls detected - yield tool info
            tools = check_response.tool_calls
            yield f"event: tool_start\ndata: {json.dumps({'tools': tools})}\n\n"

            # Execute tools and get results
            from app.services.agent import get_current_time, query_knowledge_base

            tool_results = []
            for tool_call in tools:
                tool_name = tool_call.get("name", "")
                tool_args = tool_call.get("args", {})

                if tool_name == "get_current_time":
                    result = get_current_time.invoke(tool_args)
                    tool_results.append({"name": tool_name, "result": result})
                elif tool_name == "query_knowledge_base":
                    result = query_knowledge_base.invoke(tool_args)
                    tool_results.append({"name": tool_name, "result": result})

                yield f"event: tool_result\ndata: {json.dumps({'tool': tool_name, 'result': result})}\n\n"

            # Add tool results to messages and stream final response
            for tr in tool_results:
                messages.append(AIMessage(content=f"Tool result for {tr['name']}: {tr['result']}"))

    except Exception as e:
        logger.warning(f"Tool check failed: {e}")

    # Stream the main response
    yield f"event: message_start\ndata: {json.dumps({'session_id': session_id})}\n\n"

    full_response = ""
    try:
        async for chunk in llm.astream(messages):
            if chunk.content:
                full_response += chunk.content
                # Escape newlines for SSE format
                content = chunk.content.replace("\n", "\\n")
                yield f"event: token\ndata: {json.dumps({'token': content})}\n\n"

        # Yield final message with full content
        yield f"event: message_end\ndata: {json.dumps({'full_message': full_response, 'session_id': session_id, 'tool_calls': tools if tools else None})}\n\n"

    except Exception as e:
        logger.error(f"Streaming error: {e}")
        yield f"event: error\ndata: {json.dumps({'error': str(e)})}\n\n"
